// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cash_flows.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createCashFlow = `-- name: CreateCashFlow :one
INSERT INTO cash_flow (portfolio_id, type, source_amount, source_currency, target_amount, target_currency, broker_rate, transaction_time)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, portfolio_id, type, source_amount, source_currency, target_amount, target_currency, broker_rate, transaction_time
`

type CreateCashFlowParams struct {
	PortfolioID     int64          `json:"portfolio_id"`
	Type            string         `json:"type"`
	SourceAmount    string         `json:"source_amount"`
	SourceCurrency  string         `json:"source_currency"`
	TargetAmount    string         `json:"target_amount"`
	TargetCurrency  string         `json:"target_currency"`
	BrokerRate      sql.NullString `json:"broker_rate"`
	TransactionTime time.Time      `json:"transaction_time"`
}

func (q *Queries) CreateCashFlow(ctx context.Context, arg CreateCashFlowParams) (CashFlow, error) {
	row := q.db.QueryRowContext(ctx, createCashFlow,
		arg.PortfolioID,
		arg.Type,
		arg.SourceAmount,
		arg.SourceCurrency,
		arg.TargetAmount,
		arg.TargetCurrency,
		arg.BrokerRate,
		arg.TransactionTime,
	)
	var i CashFlow
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.Type,
		&i.SourceAmount,
		&i.SourceCurrency,
		&i.TargetAmount,
		&i.TargetCurrency,
		&i.BrokerRate,
		&i.TransactionTime,
	)
	return i, err
}

const listCashFlows = `-- name: ListCashFlows :many
SELECT id, portfolio_id, type, source_amount, source_currency, target_amount, target_currency, broker_rate, transaction_time FROM cash_flow
WHERE portfolio_id = $1
  AND ($2::TIMESTAMPTZ = '0001-01-01'::TIMESTAMPTZ OR transaction_time >= $2)
  AND ($3::TIMESTAMPTZ = '0001-01-01'::TIMESTAMPTZ OR transaction_time <= $3)
ORDER BY transaction_time DESC
LIMIT $4 OFFSET $5
`

type ListCashFlowsParams struct {
	PortfolioID int64     `json:"portfolio_id"`
	Column2     time.Time `json:"column_2"`
	Column3     time.Time `json:"column_3"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListCashFlows(ctx context.Context, arg ListCashFlowsParams) ([]CashFlow, error) {
	rows, err := q.db.QueryContext(ctx, listCashFlows,
		arg.PortfolioID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CashFlow{}
	for rows.Next() {
		var i CashFlow
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.Type,
			&i.SourceAmount,
			&i.SourceCurrency,
			&i.TargetAmount,
			&i.TargetCurrency,
			&i.BrokerRate,
			&i.TransactionTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
