// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dividends.sql

package db

import (
	"context"
	"time"
)

const createDividend = `-- name: CreateDividend :one
INSERT INTO dividend (portfolio_id, ticker_id, currency, amount, transaction_time)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, portfolio_id, ticker_id, currency, amount, transaction_time
`

type CreateDividendParams struct {
	PortfolioID     int64     `json:"portfolio_id"`
	TickerID        int64     `json:"ticker_id"`
	Currency        string    `json:"currency"`
	Amount          string    `json:"amount"`
	TransactionTime time.Time `json:"transaction_time"`
}

func (q *Queries) CreateDividend(ctx context.Context, arg CreateDividendParams) (Dividend, error) {
	row := q.db.QueryRowContext(ctx, createDividend,
		arg.PortfolioID,
		arg.TickerID,
		arg.Currency,
		arg.Amount,
		arg.TransactionTime,
	)
	var i Dividend
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.TickerID,
		&i.Currency,
		&i.Amount,
		&i.TransactionTime,
	)
	return i, err
}

const listDividends = `-- name: ListDividends :many
SELECT d.id, d.portfolio_id, d.ticker_id, d.currency, d.amount, d.transaction_time, t.symbol, t.name AS ticker_name
FROM dividend d
JOIN ticker t ON t.id = d.ticker_id
WHERE d.portfolio_id = $1
ORDER BY d.transaction_time DESC
LIMIT $2 OFFSET $3
`

type ListDividendsParams struct {
	PortfolioID int64 `json:"portfolio_id"`
	Limit       int32 `json:"limit"`
	Offset      int32 `json:"offset"`
}

type ListDividendsRow struct {
	ID              int64     `json:"id"`
	PortfolioID     int64     `json:"portfolio_id"`
	TickerID        int64     `json:"ticker_id"`
	Currency        string    `json:"currency"`
	Amount          string    `json:"amount"`
	TransactionTime time.Time `json:"transaction_time"`
	Symbol          string    `json:"symbol"`
	TickerName      string    `json:"ticker_name"`
}

func (q *Queries) ListDividends(ctx context.Context, arg ListDividendsParams) ([]ListDividendsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDividends, arg.PortfolioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDividendsRow{}
	for rows.Next() {
		var i ListDividendsRow
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.TickerID,
			&i.Currency,
			&i.Amount,
			&i.TransactionTime,
			&i.Symbol,
			&i.TickerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumDividendsByPortfolio = `-- name: SumDividendsByPortfolio :one
SELECT COALESCE(SUM(amount), 0)::NUMERIC AS total_dividends
FROM dividend
WHERE portfolio_id = $1
`

func (q *Queries) SumDividendsByPortfolio(ctx context.Context, portfolioID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, sumDividendsByPortfolio, portfolioID)
	var total_dividends string
	err := row.Scan(&total_dividends)
	return total_dividends, err
}
