// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: holdings.sql

package db

import (
	"context"
	"time"
)

const deleteHolding = `-- name: DeleteHolding :exec
DELETE FROM holding
WHERE portfolio_id = $1 AND ticker_id = $2
`

type DeleteHoldingParams struct {
	PortfolioID int64 `json:"portfolio_id"`
	TickerID    int64 `json:"ticker_id"`
}

func (q *Queries) DeleteHolding(ctx context.Context, arg DeleteHoldingParams) error {
	_, err := q.db.ExecContext(ctx, deleteHolding, arg.PortfolioID, arg.TickerID)
	return err
}

const getHolding = `-- name: GetHolding :one
SELECT id, portfolio_id, ticker_id, avg, share, updated_time, created_time FROM holding
WHERE portfolio_id = $1 AND ticker_id = $2
`

type GetHoldingParams struct {
	PortfolioID int64 `json:"portfolio_id"`
	TickerID    int64 `json:"ticker_id"`
}

func (q *Queries) GetHolding(ctx context.Context, arg GetHoldingParams) (Holding, error) {
	row := q.db.QueryRowContext(ctx, getHolding, arg.PortfolioID, arg.TickerID)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.TickerID,
		&i.Avg,
		&i.Share,
		&i.UpdatedTime,
		&i.CreatedTime,
	)
	return i, err
}

const listHoldingsByPortfolio = `-- name: ListHoldingsByPortfolio :many
SELECT h.id, h.portfolio_id, h.ticker_id, h.avg, h.share, h.updated_time, h.created_time, t.symbol, t.name AS ticker_name, t.currency AS ticker_currency
FROM holding h
JOIN ticker t ON t.id = h.ticker_id
WHERE h.portfolio_id = $1
ORDER BY h.created_time ASC
`

type ListHoldingsByPortfolioRow struct {
	ID             int64     `json:"id"`
	PortfolioID    int64     `json:"portfolio_id"`
	TickerID       int64     `json:"ticker_id"`
	Avg            string    `json:"avg"`
	Share          string    `json:"share"`
	UpdatedTime    time.Time `json:"updated_time"`
	CreatedTime    time.Time `json:"created_time"`
	Symbol         string    `json:"symbol"`
	TickerName     string    `json:"ticker_name"`
	TickerCurrency string    `json:"ticker_currency"`
}

func (q *Queries) ListHoldingsByPortfolio(ctx context.Context, portfolioID int64) ([]ListHoldingsByPortfolioRow, error) {
	rows, err := q.db.QueryContext(ctx, listHoldingsByPortfolio, portfolioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHoldingsByPortfolioRow{}
	for rows.Next() {
		var i ListHoldingsByPortfolioRow
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.TickerID,
			&i.Avg,
			&i.Share,
			&i.UpdatedTime,
			&i.CreatedTime,
			&i.Symbol,
			&i.TickerName,
			&i.TickerCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHolding = `-- name: UpsertHolding :one
INSERT INTO holding (portfolio_id, ticker_id, avg, share)
VALUES ($1, $2, $3, $4)
ON CONFLICT (portfolio_id, ticker_id) DO UPDATE
    SET avg          = $3,
        share        = $4,
        updated_time = NOW()
RETURNING id, portfolio_id, ticker_id, avg, share, updated_time, created_time
`

type UpsertHoldingParams struct {
	PortfolioID int64  `json:"portfolio_id"`
	TickerID    int64  `json:"ticker_id"`
	Avg         string `json:"avg"`
	Share       string `json:"share"`
}

func (q *Queries) UpsertHolding(ctx context.Context, arg UpsertHoldingParams) (Holding, error) {
	row := q.db.QueryRowContext(ctx, upsertHolding,
		arg.PortfolioID,
		arg.TickerID,
		arg.Avg,
		arg.Share,
	)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.TickerID,
		&i.Avg,
		&i.Share,
		&i.UpdatedTime,
		&i.CreatedTime,
	)
	return i, err
}
