// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type CashFlow struct {
	ID              int64          `json:"id"`
	PortfolioID     int64          `json:"portfolio_id"`
	Type            string         `json:"type"`
	SourceAmount    string         `json:"source_amount"`
	SourceCurrency  string         `json:"source_currency"`
	TargetAmount    string         `json:"target_amount"`
	TargetCurrency  string         `json:"target_currency"`
	BrokerRate      sql.NullString `json:"broker_rate"`
	TransactionTime time.Time      `json:"transaction_time"`
}

type Dividend struct {
	ID              int64     `json:"id"`
	PortfolioID     int64     `json:"portfolio_id"`
	TickerID        int64     `json:"ticker_id"`
	Currency        string    `json:"currency"`
	Amount          string    `json:"amount"`
	TransactionTime time.Time `json:"transaction_time"`
}

type Holding struct {
	ID          int64     `json:"id"`
	PortfolioID int64     `json:"portfolio_id"`
	TickerID    int64     `json:"ticker_id"`
	Avg         string    `json:"avg"`
	Share       string    `json:"share"`
	UpdatedTime time.Time `json:"updated_time"`
	CreatedTime time.Time `json:"created_time"`
}

type Portfolio struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	Name        string    `json:"name"`
	Currency    string    `json:"currency"`
	Cash        string    `json:"cash"`
	UpdatedTime time.Time `json:"updated_time"`
	CreatedTime time.Time `json:"created_time"`
}

type PortfolioSnapshot struct {
	ID            int64     `json:"id"`
	PortfolioID   int64     `json:"portfolio_id"`
	TotalEquity   string    `json:"total_equity"`
	TotalInvested string    `json:"total_invested"`
	CashBalance   string    `json:"cash_balance"`
	Unrealized    string    `json:"unrealized"`
	Realized      string    `json:"realized"`
	Currency      string    `json:"currency"`
	SnapshotDate  time.Time `json:"snapshot_date"`
}

type Ticker struct {
	ID          int64     `json:"id"`
	Symbol      string    `json:"symbol"`
	Name        string    `json:"name"`
	Type        string    `json:"type"`
	Currency    string    `json:"currency"`
	Sector      string    `json:"sector"`
	Subsector   string    `json:"subsector"`
	UpdatedTime time.Time `json:"updated_time"`
	CreatedTime time.Time `json:"created_time"`
}

type TickerSnapshot struct {
	ID           int64     `json:"id"`
	PortfolioID  int64     `json:"portfolio_id"`
	TickerID     int64     `json:"ticker_id"`
	Price        string    `json:"price"`
	Currency     string    `json:"currency"`
	Quantity     string    `json:"quantity"`
	Avg          string    `json:"avg"`
	MarketValue  string    `json:"market_value"`
	SnapshotDate time.Time `json:"snapshot_date"`
}

type Transaction struct {
	ID              int64     `json:"id"`
	PortfolioID     int64     `json:"portfolio_id"`
	TickerID        int64     `json:"ticker_id"`
	Side            string    `json:"side"`
	Quantity        string    `json:"quantity"`
	Price           string    `json:"price"`
	RealizedGain    string    `json:"realized_gain"`
	Fee             string    `json:"fee"`
	TotalAmount     string    `json:"total_amount"`
	TransactionTime time.Time `json:"transaction_time"`
}

type User struct {
	ID            int64          `json:"id"`
	Username      string         `json:"username"`
	Email         string         `json:"email"`
	Password      string         `json:"password"`
	FinnhubApiKey sql.NullString `json:"finnhub_api_key"`
	UpdatedTime   time.Time      `json:"updated_time"`
	CreatedTime   time.Time      `json:"created_time"`
}
