// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portfolios.sql

package db

import (
	"context"
	"database/sql"
)

const createPortfolio = `-- name: CreatePortfolio :one
INSERT INTO portfolio (user_id, name, currency, cash)
VALUES ($1, $2, $3, 0)
RETURNING id, user_id, name, currency, cash, updated_time, created_time
`

type CreatePortfolioParams struct {
	UserID   int64  `json:"user_id"`
	Name     string `json:"name"`
	Currency string `json:"currency"`
}

func (q *Queries) CreatePortfolio(ctx context.Context, arg CreatePortfolioParams) (Portfolio, error) {
	row := q.db.QueryRowContext(ctx, createPortfolio, arg.UserID, arg.Name, arg.Currency)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.Cash,
		&i.UpdatedTime,
		&i.CreatedTime,
	)
	return i, err
}

const deletePortfolio = `-- name: DeletePortfolio :exec
DELETE FROM portfolio
WHERE id = $1 AND user_id = $2
`

type DeletePortfolioParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeletePortfolio(ctx context.Context, arg DeletePortfolioParams) error {
	_, err := q.db.ExecContext(ctx, deletePortfolio, arg.ID, arg.UserID)
	return err
}

const getPortfolio = `-- name: GetPortfolio :one
SELECT id, user_id, name, currency, cash, updated_time, created_time FROM portfolio
WHERE id = $1
`

func (q *Queries) GetPortfolio(ctx context.Context, id int64) (Portfolio, error) {
	row := q.db.QueryRowContext(ctx, getPortfolio, id)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.Cash,
		&i.UpdatedTime,
		&i.CreatedTime,
	)
	return i, err
}

const getPortfolioForUser = `-- name: GetPortfolioForUser :one
SELECT id, user_id, name, currency, cash, updated_time, created_time FROM portfolio
WHERE id = $1 AND user_id = $2
`

type GetPortfolioForUserParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetPortfolioForUser(ctx context.Context, arg GetPortfolioForUserParams) (Portfolio, error) {
	row := q.db.QueryRowContext(ctx, getPortfolioForUser, arg.ID, arg.UserID)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.Cash,
		&i.UpdatedTime,
		&i.CreatedTime,
	)
	return i, err
}

const listAllPortfolios = `-- name: ListAllPortfolios :many
SELECT id, user_id, name, currency, cash, updated_time, created_time FROM portfolio ORDER BY id ASC
`

func (q *Queries) ListAllPortfolios(ctx context.Context) ([]Portfolio, error) {
	rows, err := q.db.QueryContext(ctx, listAllPortfolios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Portfolio{}
	for rows.Next() {
		var i Portfolio
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Currency,
			&i.Cash,
			&i.UpdatedTime,
			&i.CreatedTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortfoliosByUser = `-- name: ListPortfoliosByUser :many
SELECT id, user_id, name, currency, cash, updated_time, created_time FROM portfolio
WHERE user_id = $1
ORDER BY created_time ASC
`

func (q *Queries) ListPortfoliosByUser(ctx context.Context, userID int64) ([]Portfolio, error) {
	rows, err := q.db.QueryContext(ctx, listPortfoliosByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Portfolio{}
	for rows.Next() {
		var i Portfolio
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Currency,
			&i.Cash,
			&i.UpdatedTime,
			&i.CreatedTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePortfolio = `-- name: UpdatePortfolio :one
UPDATE portfolio
SET name         = COALESCE($3, name),
    currency     = COALESCE($4, currency),
    updated_time = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, currency, cash, updated_time, created_time
`

type UpdatePortfolioParams struct {
	ID       int64          `json:"id"`
	UserID   int64          `json:"user_id"`
	Name     sql.NullString `json:"name"`
	Currency sql.NullString `json:"currency"`
}

func (q *Queries) UpdatePortfolio(ctx context.Context, arg UpdatePortfolioParams) (Portfolio, error) {
	row := q.db.QueryRowContext(ctx, updatePortfolio,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Currency,
	)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.Cash,
		&i.UpdatedTime,
		&i.CreatedTime,
	)
	return i, err
}

const updatePortfolioCash = `-- name: UpdatePortfolioCash :one
UPDATE portfolio
SET cash         = $2,
    updated_time = NOW()
WHERE id = $1
RETURNING id, user_id, name, currency, cash, updated_time, created_time
`

type UpdatePortfolioCashParams struct {
	ID   int64  `json:"id"`
	Cash string `json:"cash"`
}

func (q *Queries) UpdatePortfolioCash(ctx context.Context, arg UpdatePortfolioCashParams) (Portfolio, error) {
	row := q.db.QueryRowContext(ctx, updatePortfolioCash, arg.ID, arg.Cash)
	var i Portfolio
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.Cash,
		&i.UpdatedTime,
		&i.CreatedTime,
	)
	return i, err
}
