// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portfolio_fees.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createPortfolioFee = `-- name: CreatePortfolioFee :one
INSERT INTO portfolio_fee (portfolio_id, amount, note, transaction_time)
VALUES ($1, $2, $3, $4)
RETURNING id, portfolio_id, amount, note, transaction_time
`

type CreatePortfolioFeeParams struct {
	PortfolioID     int64          `json:"portfolio_id"`
	Amount          string         `json:"amount"`
	Note            sql.NullString `json:"note"`
	TransactionTime time.Time      `json:"transaction_time"`
}

func (q *Queries) CreatePortfolioFee(ctx context.Context, arg CreatePortfolioFeeParams) (PortfolioFee, error) {
	row := q.db.QueryRowContext(ctx, createPortfolioFee,
		arg.PortfolioID,
		arg.Amount,
		arg.Note,
		arg.TransactionTime,
	)
	var i PortfolioFee
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.Amount,
		&i.Note,
		&i.TransactionTime,
	)
	return i, err
}

const listPortfolioFees = `-- name: ListPortfolioFees :many
SELECT id, portfolio_id, amount, note, transaction_time FROM portfolio_fee
WHERE portfolio_id = $1
ORDER BY transaction_time DESC
LIMIT $2 OFFSET $3
`

type ListPortfolioFeesParams struct {
	PortfolioID int64 `json:"portfolio_id"`
	Limit       int32 `json:"limit"`
	Offset      int32 `json:"offset"`
}

func (q *Queries) ListPortfolioFees(ctx context.Context, arg ListPortfolioFeesParams) ([]PortfolioFee, error) {
	rows, err := q.db.QueryContext(ctx, listPortfolioFees, arg.PortfolioID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortfolioFee{}
	for rows.Next() {
		var i PortfolioFee
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.Amount,
			&i.Note,
			&i.TransactionTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
