// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: snapshots.sql

package db

import (
	"context"
	"time"
)

const listNetWorthSnapshots = `-- name: ListNetWorthSnapshots :many
WITH portfolio_daily AS (
    SELECT ps.snapshot_date,
           SUM(CASE WHEN ps.currency = 'IDR'
                    THEN (ps.total_equity + ps.cash_balance) * $4::NUMERIC
                    ELSE  (ps.total_equity + ps.cash_balance) * $5::NUMERIC END) AS portfolio_nw,
           SUM(CASE WHEN ps.currency = 'IDR'
                    THEN ps.total_invested * $4::NUMERIC
                    ELSE ps.total_invested * $5::NUMERIC END)                     AS total_invested,
           SUM(CASE WHEN ps.currency = 'IDR'
                    THEN ps.unrealized * $4::NUMERIC
                    ELSE ps.unrealized * $5::NUMERIC END)                         AS unrealized,
           SUM(CASE WHEN ps.currency = 'IDR'
                    THEN ps.realized * $4::NUMERIC
                    ELSE ps.realized * $5::NUMERIC END)                           AS realized,
           SUM(CASE WHEN ps.currency = 'IDR'
                    THEN ps.cash_balance * $4::NUMERIC
                    ELSE ps.cash_balance * $5::NUMERIC END)                       AS portfolio_cash
    FROM portfolio_snapshot ps
    JOIN portfolio p ON p.id = ps.portfolio_id
    WHERE p.user_id = $1
      AND ps.snapshot_date >= $2
      AND ps.snapshot_date <= $3
    GROUP BY ps.snapshot_date
),
wallet_daily AS (
    SELECT ws.snapshot_date,
           SUM(ws.balance_usd * $5::NUMERIC) AS wallet_usd
    FROM wallet_snapshot ws
    JOIN wallet w ON w.id = ws.wallet_id
    WHERE w.user_id = $1
      AND ws.snapshot_date >= $2
      AND ws.snapshot_date <= $3
    GROUP BY ws.snapshot_date
),
all_dates AS (
    SELECT snapshot_date FROM portfolio_daily
    UNION
    SELECT snapshot_date FROM wallet_daily
)
SELECT
    d.snapshot_date,
    (COALESCE(pd.portfolio_nw, 0)   + COALESCE(wd.wallet_usd, 0))::NUMERIC AS net_worth,
    COALESCE(pd.total_invested, 0)::NUMERIC                                  AS total_invested,
    COALESCE(pd.unrealized, 0)::NUMERIC                                      AS unrealized,
    COALESCE(pd.realized, 0)::NUMERIC                                        AS realized,
    (COALESCE(pd.portfolio_cash, 0) + COALESCE(wd.wallet_usd, 0))::NUMERIC  AS cash_balance
FROM all_dates d
LEFT JOIN portfolio_daily pd ON pd.snapshot_date = d.snapshot_date
LEFT JOIN wallet_daily    wd ON wd.snapshot_date = d.snapshot_date
ORDER BY d.snapshot_date ASC
`

type ListNetWorthSnapshotsParams struct {
	UserID         int64     `json:"user_id"`
	SnapshotDate   time.Time `json:"snapshot_date"`
	SnapshotDate_2 time.Time `json:"snapshot_date_2"`
	Column4        string    `json:"column_4"`
	Column5        string    `json:"column_5"`
}

type ListNetWorthSnapshotsRow struct {
	SnapshotDate  time.Time `json:"snapshot_date"`
	NetWorth      string    `json:"net_worth"`
	TotalInvested string    `json:"total_invested"`
	Unrealized    string    `json:"unrealized"`
	Realized      string    `json:"realized"`
	CashBalance   string    `json:"cash_balance"`
}

func (q *Queries) ListNetWorthSnapshots(ctx context.Context, arg ListNetWorthSnapshotsParams) ([]ListNetWorthSnapshotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNetWorthSnapshots,
		arg.UserID,
		arg.SnapshotDate,
		arg.SnapshotDate_2,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNetWorthSnapshotsRow{}
	for rows.Next() {
		var i ListNetWorthSnapshotsRow
		if err := rows.Scan(
			&i.SnapshotDate,
			&i.NetWorth,
			&i.TotalInvested,
			&i.Unrealized,
			&i.Realized,
			&i.CashBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortfolioSnapshots = `-- name: ListPortfolioSnapshots :many
SELECT id, portfolio_id, total_equity, total_invested, cash_balance, unrealized, realized, currency, snapshot_date FROM portfolio_snapshot
WHERE portfolio_id = $1
  AND snapshot_date >= $2
  AND snapshot_date <= $3
ORDER BY snapshot_date ASC
`

type ListPortfolioSnapshotsParams struct {
	PortfolioID    int64     `json:"portfolio_id"`
	SnapshotDate   time.Time `json:"snapshot_date"`
	SnapshotDate_2 time.Time `json:"snapshot_date_2"`
}

func (q *Queries) ListPortfolioSnapshots(ctx context.Context, arg ListPortfolioSnapshotsParams) ([]PortfolioSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listPortfolioSnapshots, arg.PortfolioID, arg.SnapshotDate, arg.SnapshotDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PortfolioSnapshot{}
	for rows.Next() {
		var i PortfolioSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.TotalEquity,
			&i.TotalInvested,
			&i.CashBalance,
			&i.Unrealized,
			&i.Realized,
			&i.Currency,
			&i.SnapshotDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPortfolioSnapshot = `-- name: UpsertPortfolioSnapshot :one
INSERT INTO portfolio_snapshot (portfolio_id, total_equity, total_invested, cash_balance, unrealized, realized, currency, snapshot_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (portfolio_id, snapshot_date) DO UPDATE
    SET total_equity   = EXCLUDED.total_equity,
        total_invested = EXCLUDED.total_invested,
        cash_balance   = EXCLUDED.cash_balance,
        unrealized     = EXCLUDED.unrealized,
        realized       = EXCLUDED.realized,
        currency       = EXCLUDED.currency
RETURNING id, portfolio_id, total_equity, total_invested, cash_balance, unrealized, realized, currency, snapshot_date
`

type UpsertPortfolioSnapshotParams struct {
	PortfolioID   int64     `json:"portfolio_id"`
	TotalEquity   string    `json:"total_equity"`
	TotalInvested string    `json:"total_invested"`
	CashBalance   string    `json:"cash_balance"`
	Unrealized    string    `json:"unrealized"`
	Realized      string    `json:"realized"`
	Currency      string    `json:"currency"`
	SnapshotDate  time.Time `json:"snapshot_date"`
}

func (q *Queries) UpsertPortfolioSnapshot(ctx context.Context, arg UpsertPortfolioSnapshotParams) (PortfolioSnapshot, error) {
	row := q.db.QueryRowContext(ctx, upsertPortfolioSnapshot,
		arg.PortfolioID,
		arg.TotalEquity,
		arg.TotalInvested,
		arg.CashBalance,
		arg.Unrealized,
		arg.Realized,
		arg.Currency,
		arg.SnapshotDate,
	)
	var i PortfolioSnapshot
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.TotalEquity,
		&i.TotalInvested,
		&i.CashBalance,
		&i.Unrealized,
		&i.Realized,
		&i.Currency,
		&i.SnapshotDate,
	)
	return i, err
}

const upsertTickerSnapshot = `-- name: UpsertTickerSnapshot :one
INSERT INTO ticker_snapshot (portfolio_id, ticker_id, price, currency, quantity, avg, market_value, snapshot_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (portfolio_id, ticker_id, snapshot_date) DO UPDATE
    SET price        = EXCLUDED.price,
        currency     = EXCLUDED.currency,
        quantity     = EXCLUDED.quantity,
        avg          = EXCLUDED.avg,
        market_value = EXCLUDED.market_value
RETURNING id, portfolio_id, ticker_id, price, currency, quantity, avg, market_value, snapshot_date
`

type UpsertTickerSnapshotParams struct {
	PortfolioID  int64     `json:"portfolio_id"`
	TickerID     int64     `json:"ticker_id"`
	Price        string    `json:"price"`
	Currency     string    `json:"currency"`
	Quantity     string    `json:"quantity"`
	Avg          string    `json:"avg"`
	MarketValue  string    `json:"market_value"`
	SnapshotDate time.Time `json:"snapshot_date"`
}

func (q *Queries) UpsertTickerSnapshot(ctx context.Context, arg UpsertTickerSnapshotParams) (TickerSnapshot, error) {
	row := q.db.QueryRowContext(ctx, upsertTickerSnapshot,
		arg.PortfolioID,
		arg.TickerID,
		arg.Price,
		arg.Currency,
		arg.Quantity,
		arg.Avg,
		arg.MarketValue,
		arg.SnapshotDate,
	)
	var i TickerSnapshot
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.TickerID,
		&i.Price,
		&i.Currency,
		&i.Quantity,
		&i.Avg,
		&i.MarketValue,
		&i.SnapshotDate,
	)
	return i, err
}
