// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tickers.sql

package db

import (
	"context"
)

const getOrCreateTicker = `-- name: GetOrCreateTicker :one
INSERT INTO ticker (symbol, name, type, currency, sector, subsector)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (symbol) DO UPDATE
    SET name         = EXCLUDED.name,
        type         = EXCLUDED.type,
        currency     = EXCLUDED.currency,
        sector       = EXCLUDED.sector,
        subsector    = EXCLUDED.subsector,
        updated_time = NOW()
RETURNING id, symbol, name, type, currency, sector, subsector, updated_time, created_time
`

type GetOrCreateTickerParams struct {
	Symbol    string `json:"symbol"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	Currency  string `json:"currency"`
	Sector    string `json:"sector"`
	Subsector string `json:"subsector"`
}

func (q *Queries) GetOrCreateTicker(ctx context.Context, arg GetOrCreateTickerParams) (Ticker, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateTicker,
		arg.Symbol,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.Sector,
		arg.Subsector,
	)
	var i Ticker
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Sector,
		&i.Subsector,
		&i.UpdatedTime,
		&i.CreatedTime,
	)
	return i, err
}

const getTickerByID = `-- name: GetTickerByID :one
SELECT id, symbol, name, type, currency, sector, subsector, updated_time, created_time FROM ticker
WHERE id = $1
`

func (q *Queries) GetTickerByID(ctx context.Context, id int64) (Ticker, error) {
	row := q.db.QueryRowContext(ctx, getTickerByID, id)
	var i Ticker
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Sector,
		&i.Subsector,
		&i.UpdatedTime,
		&i.CreatedTime,
	)
	return i, err
}

const getTickerBySymbol = `-- name: GetTickerBySymbol :one
SELECT id, symbol, name, type, currency, sector, subsector, updated_time, created_time FROM ticker
WHERE symbol = $1
`

func (q *Queries) GetTickerBySymbol(ctx context.Context, symbol string) (Ticker, error) {
	row := q.db.QueryRowContext(ctx, getTickerBySymbol, symbol)
	var i Ticker
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Sector,
		&i.Subsector,
		&i.UpdatedTime,
		&i.CreatedTime,
	)
	return i, err
}
