// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"
	"time"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transaction (portfolio_id, ticker_id, side, quantity, price, realized_gain, fee, total_amount, transaction_time)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, portfolio_id, ticker_id, side, quantity, price, realized_gain, fee, total_amount, transaction_time
`

type CreateTransactionParams struct {
	PortfolioID     int64     `json:"portfolio_id"`
	TickerID        int64     `json:"ticker_id"`
	Side            string    `json:"side"`
	Quantity        string    `json:"quantity"`
	Price           string    `json:"price"`
	RealizedGain    string    `json:"realized_gain"`
	Fee             string    `json:"fee"`
	TotalAmount     string    `json:"total_amount"`
	TransactionTime time.Time `json:"transaction_time"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.PortfolioID,
		arg.TickerID,
		arg.Side,
		arg.Quantity,
		arg.Price,
		arg.RealizedGain,
		arg.Fee,
		arg.TotalAmount,
		arg.TransactionTime,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.TickerID,
		&i.Side,
		&i.Quantity,
		&i.Price,
		&i.RealizedGain,
		&i.Fee,
		&i.TotalAmount,
		&i.TransactionTime,
	)
	return i, err
}

const getPortfolioCashAsOf = `-- name: GetPortfolioCashAsOf :one
SELECT (
    COALESCE((SELECT SUM(cf.target_amount) FROM cash_flow cf
              WHERE cf.portfolio_id = $1 AND cf.type = 'DEPOSIT'    AND cf.transaction_time <= $2), 0)
  - COALESCE((SELECT SUM(cf.source_amount) FROM cash_flow cf
              WHERE cf.portfolio_id = $1 AND cf.type = 'WITHDRAWAL' AND cf.transaction_time <= $2), 0)
  - COALESCE((SELECT SUM(t.total_amount) FROM transaction t
              WHERE t.portfolio_id = $1 AND t.side = 'BUY'  AND t.transaction_time <= $2), 0)
  + COALESCE((SELECT SUM(t.total_amount) FROM transaction t
              WHERE t.portfolio_id = $1 AND t.side = 'SELL' AND t.transaction_time <= $2), 0)
  + COALESCE((SELECT SUM(d.amount) FROM dividend d
              WHERE d.portfolio_id = $1 AND d.transaction_time <= $2), 0)
  - COALESCE((SELECT SUM(f.amount) FROM portfolio_fee f
              WHERE f.portfolio_id = $1 AND f.transaction_time <= $2), 0)
)::NUMERIC AS cash
`

type GetPortfolioCashAsOfParams struct {
	PortfolioID     int64     `json:"portfolio_id"`
	TransactionTime time.Time `json:"transaction_time"`
}

func (q *Queries) GetPortfolioCashAsOf(ctx context.Context, arg GetPortfolioCashAsOfParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getPortfolioCashAsOf, arg.PortfolioID, arg.TransactionTime)
	var cash string
	err := row.Scan(&cash)
	return cash, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT t.id, t.portfolio_id, t.ticker_id, t.side, t.quantity, t.price, t.realized_gain, t.fee, t.total_amount, t.transaction_time, tk.symbol, tk.name AS ticker_name
FROM transaction t
JOIN ticker tk ON tk.id = t.ticker_id
WHERE t.id = $1 AND t.portfolio_id = $2
`

type GetTransactionParams struct {
	ID          int64 `json:"id"`
	PortfolioID int64 `json:"portfolio_id"`
}

type GetTransactionRow struct {
	ID              int64     `json:"id"`
	PortfolioID     int64     `json:"portfolio_id"`
	TickerID        int64     `json:"ticker_id"`
	Side            string    `json:"side"`
	Quantity        string    `json:"quantity"`
	Price           string    `json:"price"`
	RealizedGain    string    `json:"realized_gain"`
	Fee             string    `json:"fee"`
	TotalAmount     string    `json:"total_amount"`
	TransactionTime time.Time `json:"transaction_time"`
	Symbol          string    `json:"symbol"`
	TickerName      string    `json:"ticker_name"`
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (GetTransactionRow, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, arg.ID, arg.PortfolioID)
	var i GetTransactionRow
	err := row.Scan(
		&i.ID,
		&i.PortfolioID,
		&i.TickerID,
		&i.Side,
		&i.Quantity,
		&i.Price,
		&i.RealizedGain,
		&i.Fee,
		&i.TotalAmount,
		&i.TransactionTime,
		&i.Symbol,
		&i.TickerName,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT t.id, t.portfolio_id, t.ticker_id, t.side, t.quantity, t.price, t.realized_gain, t.fee, t.total_amount, t.transaction_time, tk.symbol, tk.name AS ticker_name
FROM transaction t
JOIN ticker tk ON tk.id = t.ticker_id
WHERE t.portfolio_id = $1
  AND ($2 = '' OR tk.symbol = $2)
  AND ($3 = '' OR t.side = $3)
  AND ($4::TIMESTAMPTZ = '0001-01-01'::TIMESTAMPTZ OR t.transaction_time >= $4)
  AND ($5::TIMESTAMPTZ = '0001-01-01'::TIMESTAMPTZ OR t.transaction_time <= $5)
ORDER BY t.transaction_time DESC
LIMIT $6 OFFSET $7
`

type ListTransactionsParams struct {
	PortfolioID int64       `json:"portfolio_id"`
	Column2     interface{} `json:"column_2"`
	Column3     interface{} `json:"column_3"`
	Column4     time.Time   `json:"column_4"`
	Column5     time.Time   `json:"column_5"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

type ListTransactionsRow struct {
	ID              int64     `json:"id"`
	PortfolioID     int64     `json:"portfolio_id"`
	TickerID        int64     `json:"ticker_id"`
	Side            string    `json:"side"`
	Quantity        string    `json:"quantity"`
	Price           string    `json:"price"`
	RealizedGain    string    `json:"realized_gain"`
	Fee             string    `json:"fee"`
	TotalAmount     string    `json:"total_amount"`
	TransactionTime time.Time `json:"transaction_time"`
	Symbol          string    `json:"symbol"`
	TickerName      string    `json:"ticker_name"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions,
		arg.PortfolioID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsRow{}
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.TickerID,
			&i.Side,
			&i.Quantity,
			&i.Price,
			&i.RealizedGain,
			&i.Fee,
			&i.TotalAmount,
			&i.TransactionTime,
			&i.Symbol,
			&i.TickerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByPortfolioAsc = `-- name: ListTransactionsByPortfolioAsc :many
SELECT t.id, t.portfolio_id, t.ticker_id, t.side, t.quantity, t.price, t.realized_gain, t.fee, t.total_amount, t.transaction_time, tk.symbol, tk.currency AS ticker_currency
FROM transaction t
JOIN ticker tk ON tk.id = t.ticker_id
WHERE t.portfolio_id = $1
ORDER BY t.transaction_time ASC
`

type ListTransactionsByPortfolioAscRow struct {
	ID              int64     `json:"id"`
	PortfolioID     int64     `json:"portfolio_id"`
	TickerID        int64     `json:"ticker_id"`
	Side            string    `json:"side"`
	Quantity        string    `json:"quantity"`
	Price           string    `json:"price"`
	RealizedGain    string    `json:"realized_gain"`
	Fee             string    `json:"fee"`
	TotalAmount     string    `json:"total_amount"`
	TransactionTime time.Time `json:"transaction_time"`
	Symbol          string    `json:"symbol"`
	TickerCurrency  string    `json:"ticker_currency"`
}

func (q *Queries) ListTransactionsByPortfolioAsc(ctx context.Context, portfolioID int64) ([]ListTransactionsByPortfolioAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByPortfolioAsc, portfolioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsByPortfolioAscRow{}
	for rows.Next() {
		var i ListTransactionsByPortfolioAscRow
		if err := rows.Scan(
			&i.ID,
			&i.PortfolioID,
			&i.TickerID,
			&i.Side,
			&i.Quantity,
			&i.Price,
			&i.RealizedGain,
			&i.Fee,
			&i.TotalAmount,
			&i.TransactionTime,
			&i.Symbol,
			&i.TickerCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumFeesByPortfolio = `-- name: SumFeesByPortfolio :one
SELECT COALESCE(SUM(fee), 0)::NUMERIC AS total_fees
FROM transaction
WHERE portfolio_id = $1
`

func (q *Queries) SumFeesByPortfolio(ctx context.Context, portfolioID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, sumFeesByPortfolio, portfolioID)
	var total_fees string
	err := row.Scan(&total_fees)
	return total_fees, err
}

const sumRealizedGainByPortfolio = `-- name: SumRealizedGainByPortfolio :one
SELECT (
    COALESCE((SELECT SUM(t.realized_gain) FROM transaction t WHERE t.portfolio_id = $1 AND t.side = 'SELL'), 0)
    + COALESCE((SELECT SUM(d.amount) FROM dividend d WHERE d.portfolio_id = $1), 0)
    - COALESCE((SELECT SUM(f.amount) FROM portfolio_fee f WHERE f.portfolio_id = $1), 0)
)::NUMERIC AS total_realized_gain
`

func (q *Queries) SumRealizedGainByPortfolio(ctx context.Context, portfolioID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, sumRealizedGainByPortfolio, portfolioID)
	var total_realized_gain string
	err := row.Scan(&total_realized_gain)
	return total_realized_gain, err
}

const sumRealizedGainByPortfolioBefore = `-- name: SumRealizedGainByPortfolioBefore :one
SELECT (
    COALESCE((SELECT SUM(t.realized_gain) FROM transaction t
              WHERE t.portfolio_id = $1 AND t.side = 'SELL' AND t.transaction_time <= $2), 0)
  + COALESCE((SELECT SUM(d.amount) FROM dividend d
              WHERE d.portfolio_id = $1 AND d.transaction_time <= $2), 0)
  - COALESCE((SELECT SUM(f.amount) FROM portfolio_fee f
              WHERE f.portfolio_id = $1 AND f.transaction_time <= $2), 0)
)::NUMERIC AS total_realized_gain
`

type SumRealizedGainByPortfolioBeforeParams struct {
	PortfolioID     int64     `json:"portfolio_id"`
	TransactionTime time.Time `json:"transaction_time"`
}

func (q *Queries) SumRealizedGainByPortfolioBefore(ctx context.Context, arg SumRealizedGainByPortfolioBeforeParams) (string, error) {
	row := q.db.QueryRowContext(ctx, sumRealizedGainByPortfolioBefore, arg.PortfolioID, arg.TransactionTime)
	var total_realized_gain string
	err := row.Scan(&total_realized_gain)
	return total_realized_gain, err
}
