// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (username, email, password, finnhub_api_key)
VALUES ($1, $2, $3, $4)
RETURNING id, username, email, password, finnhub_api_key, updated_time, created_time
`

type CreateUserParams struct {
	Username      string         `json:"username"`
	Email         string         `json:"email"`
	Password      string         `json:"password"`
	FinnhubApiKey sql.NullString `json:"finnhub_api_key"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.FinnhubApiKey,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.FinnhubApiKey,
		&i.UpdatedTime,
		&i.CreatedTime,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password, finnhub_api_key, updated_time, created_time FROM "user"
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.FinnhubApiKey,
		&i.UpdatedTime,
		&i.CreatedTime,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password, finnhub_api_key, updated_time, created_time FROM "user"
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.FinnhubApiKey,
		&i.UpdatedTime,
		&i.CreatedTime,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE "user"
SET username        = COALESCE($2, username),
    email           = COALESCE($3, email),
    finnhub_api_key = COALESCE($4, finnhub_api_key),
    updated_time    = NOW()
WHERE id = $1
RETURNING id, username, email, password, finnhub_api_key, updated_time, created_time
`

type UpdateUserParams struct {
	ID            int64          `json:"id"`
	Username      sql.NullString `json:"username"`
	Email         sql.NullString `json:"email"`
	FinnhubApiKey sql.NullString `json:"finnhub_api_key"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.FinnhubApiKey,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.FinnhubApiKey,
		&i.UpdatedTime,
		&i.CreatedTime,
	)
	return i, err
}
