// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallet_snapshot.sql

package db

import (
	"context"
	"time"
)

const getAggregatedWalletSnapshots = `-- name: GetAggregatedWalletSnapshots :many
SELECT
    ws.snapshot_date,
    SUM(ws.balance::numeric)::text AS total_balance
FROM wallet_snapshot ws
JOIN wallet w ON w.id = ws.wallet_id
WHERE w.user_id = $1
  AND ws.snapshot_date >= $2
  AND ws.snapshot_date <= $3
GROUP BY ws.snapshot_date
ORDER BY ws.snapshot_date ASC
`

type GetAggregatedWalletSnapshotsParams struct {
	UserID         int64     `json:"user_id"`
	SnapshotDate   time.Time `json:"snapshot_date"`
	SnapshotDate_2 time.Time `json:"snapshot_date_2"`
}

type GetAggregatedWalletSnapshotsRow struct {
	SnapshotDate time.Time `json:"snapshot_date"`
	TotalBalance string    `json:"total_balance"`
}

func (q *Queries) GetAggregatedWalletSnapshots(ctx context.Context, arg GetAggregatedWalletSnapshotsParams) ([]GetAggregatedWalletSnapshotsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAggregatedWalletSnapshots, arg.UserID, arg.SnapshotDate, arg.SnapshotDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAggregatedWalletSnapshotsRow{}
	for rows.Next() {
		var i GetAggregatedWalletSnapshotsRow
		if err := rows.Scan(&i.SnapshotDate, &i.TotalBalance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletSnapshots = `-- name: ListWalletSnapshots :many
SELECT id, wallet_id, balance, balance_usd, snapshot_date FROM wallet_snapshot
WHERE wallet_id = $1
  AND snapshot_date >= $2
  AND snapshot_date <= $3
ORDER BY snapshot_date ASC
`

type ListWalletSnapshotsParams struct {
	WalletID       int64     `json:"wallet_id"`
	SnapshotDate   time.Time `json:"snapshot_date"`
	SnapshotDate_2 time.Time `json:"snapshot_date_2"`
}

func (q *Queries) ListWalletSnapshots(ctx context.Context, arg ListWalletSnapshotsParams) ([]WalletSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listWalletSnapshots, arg.WalletID, arg.SnapshotDate, arg.SnapshotDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletSnapshot{}
	for rows.Next() {
		var i WalletSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Balance,
			&i.BalanceUsd,
			&i.SnapshotDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWalletSnapshot = `-- name: UpsertWalletSnapshot :one
INSERT INTO wallet_snapshot (wallet_id, balance, balance_usd, snapshot_date)
VALUES ($1, $2, $3, $4)
ON CONFLICT (wallet_id, snapshot_date) DO UPDATE
    SET balance     = EXCLUDED.balance,
        balance_usd = EXCLUDED.balance_usd
RETURNING id, wallet_id, balance, balance_usd, snapshot_date
`

type UpsertWalletSnapshotParams struct {
	WalletID     int64     `json:"wallet_id"`
	Balance      string    `json:"balance"`
	BalanceUsd   string    `json:"balance_usd"`
	SnapshotDate time.Time `json:"snapshot_date"`
}

func (q *Queries) UpsertWalletSnapshot(ctx context.Context, arg UpsertWalletSnapshotParams) (WalletSnapshot, error) {
	row := q.db.QueryRowContext(ctx, upsertWalletSnapshot,
		arg.WalletID,
		arg.Balance,
		arg.BalanceUsd,
		arg.SnapshotDate,
	)
	var i WalletSnapshot
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Balance,
		&i.BalanceUsd,
		&i.SnapshotDate,
	)
	return i, err
}
