// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallet_transaction.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createWalletTransaction = `-- name: CreateWalletTransaction :one
INSERT INTO wallet_transaction (
    wallet_id, type, amount, category_id,
    related_wallet_id, related_portfolio_id, broker_rate, note, transaction_time, paired_transaction_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, wallet_id, type, amount, category_id, related_wallet_id, related_portfolio_id, broker_rate, note, transaction_time, paired_transaction_id
`

type CreateWalletTransactionParams struct {
	WalletID            int64          `json:"wallet_id"`
	Type                string         `json:"type"`
	Amount              string         `json:"amount"`
	CategoryID          sql.NullInt64  `json:"category_id"`
	RelatedWalletID     sql.NullInt64  `json:"related_wallet_id"`
	RelatedPortfolioID  sql.NullInt64  `json:"related_portfolio_id"`
	BrokerRate          sql.NullString `json:"broker_rate"`
	Note                sql.NullString `json:"note"`
	TransactionTime     time.Time      `json:"transaction_time"`
	PairedTransactionID sql.NullInt64  `json:"paired_transaction_id"`
}

func (q *Queries) CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (WalletTransaction, error) {
	row := q.db.QueryRowContext(ctx, createWalletTransaction,
		arg.WalletID,
		arg.Type,
		arg.Amount,
		arg.CategoryID,
		arg.RelatedWalletID,
		arg.RelatedPortfolioID,
		arg.BrokerRate,
		arg.Note,
		arg.TransactionTime,
		arg.PairedTransactionID,
	)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Type,
		&i.Amount,
		&i.CategoryID,
		&i.RelatedWalletID,
		&i.RelatedPortfolioID,
		&i.BrokerRate,
		&i.Note,
		&i.TransactionTime,
		&i.PairedTransactionID,
	)
	return i, err
}

const deleteWalletTransaction = `-- name: DeleteWalletTransaction :exec
DELETE FROM wallet_transaction WHERE id = $1 AND wallet_id = $2
`

type DeleteWalletTransactionParams struct {
	ID       int64 `json:"id"`
	WalletID int64 `json:"wallet_id"`
}

func (q *Queries) DeleteWalletTransaction(ctx context.Context, arg DeleteWalletTransactionParams) error {
	_, err := q.db.ExecContext(ctx, deleteWalletTransaction, arg.ID, arg.WalletID)
	return err
}

const deleteWalletTransactionWithPair = `-- name: DeleteWalletTransactionWithPair :exec
DELETE FROM wallet_transaction
WHERE wallet_transaction.id = $1
   OR wallet_transaction.id = (SELECT paired_transaction_id FROM wallet_transaction wt2 WHERE wt2.id = $1)
`

func (q *Queries) DeleteWalletTransactionWithPair(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteWalletTransactionWithPair, id)
	return err
}

const getAggregatedWalletCategoryBreakdown = `-- name: GetAggregatedWalletCategoryBreakdown :many
SELECT
    wc.id AS category_id,
    wc.name AS category_name,
    wc.type AS category_type,
    COALESCE(SUM(wt.amount), 0)::text AS total
FROM wallet_transaction wt
JOIN wallet_category wc ON wc.id = wt.category_id
JOIN wallet w ON w.id = wt.wallet_id
WHERE w.user_id = $1
  AND wt.transaction_time >= $2
  AND wt.transaction_time < $3
  AND wt.type IN ('INCOME', 'EXPENSE')
GROUP BY wc.id, wc.name, wc.type
ORDER BY total DESC
`

type GetAggregatedWalletCategoryBreakdownParams struct {
	UserID            int64     `json:"user_id"`
	TransactionTime   time.Time `json:"transaction_time"`
	TransactionTime_2 time.Time `json:"transaction_time_2"`
}

type GetAggregatedWalletCategoryBreakdownRow struct {
	CategoryID   int64  `json:"category_id"`
	CategoryName string `json:"category_name"`
	CategoryType string `json:"category_type"`
	Total        string `json:"total"`
}

func (q *Queries) GetAggregatedWalletCategoryBreakdown(ctx context.Context, arg GetAggregatedWalletCategoryBreakdownParams) ([]GetAggregatedWalletCategoryBreakdownRow, error) {
	rows, err := q.db.QueryContext(ctx, getAggregatedWalletCategoryBreakdown, arg.UserID, arg.TransactionTime, arg.TransactionTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAggregatedWalletCategoryBreakdownRow{}
	for rows.Next() {
		var i GetAggregatedWalletCategoryBreakdownRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryType,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAggregatedWalletSummary = `-- name: GetAggregatedWalletSummary :one
SELECT
    COALESCE(SUM(CASE WHEN wt.type IN ('INCOME','TRANSFER_IN','PORTFOLIO_WITHDRAWAL') THEN wt.amount ELSE 0 END), 0)::text AS total_income,
    COALESCE(SUM(CASE WHEN wt.type IN ('EXPENSE','TRANSFER_OUT','PORTFOLIO_DEPOSIT') THEN wt.amount ELSE 0 END), 0)::text AS total_expense
FROM wallet_transaction wt
JOIN wallet w ON w.id = wt.wallet_id
WHERE w.user_id = $1
  AND wt.transaction_time >= $2
  AND wt.transaction_time < $3
`

type GetAggregatedWalletSummaryParams struct {
	UserID            int64     `json:"user_id"`
	TransactionTime   time.Time `json:"transaction_time"`
	TransactionTime_2 time.Time `json:"transaction_time_2"`
}

type GetAggregatedWalletSummaryRow struct {
	TotalIncome  string `json:"total_income"`
	TotalExpense string `json:"total_expense"`
}

func (q *Queries) GetAggregatedWalletSummary(ctx context.Context, arg GetAggregatedWalletSummaryParams) (GetAggregatedWalletSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getAggregatedWalletSummary, arg.UserID, arg.TransactionTime, arg.TransactionTime_2)
	var i GetAggregatedWalletSummaryRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpense)
	return i, err
}

const getWalletBalance = `-- name: GetWalletBalance :one
SELECT COALESCE(
    SUM(CASE
        WHEN type IN ('INCOME', 'TRANSFER_IN', 'PORTFOLIO_WITHDRAWAL') THEN amount
        ELSE -amount
    END), 0
)::NUMERIC AS balance
FROM wallet_transaction
WHERE wallet_id = $1
`

func (q *Queries) GetWalletBalance(ctx context.Context, walletID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getWalletBalance, walletID)
	var balance string
	err := row.Scan(&balance)
	return balance, err
}

const getWalletBalanceAsOf = `-- name: GetWalletBalanceAsOf :one
SELECT COALESCE(
    SUM(CASE
        WHEN type IN ('INCOME', 'TRANSFER_IN', 'PORTFOLIO_WITHDRAWAL') THEN amount
        ELSE -amount
    END), 0
)::NUMERIC AS balance
FROM wallet_transaction
WHERE wallet_id = $1
  AND transaction_time <= $2
`

type GetWalletBalanceAsOfParams struct {
	WalletID        int64     `json:"wallet_id"`
	TransactionTime time.Time `json:"transaction_time"`
}

func (q *Queries) GetWalletBalanceAsOf(ctx context.Context, arg GetWalletBalanceAsOfParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getWalletBalanceAsOf, arg.WalletID, arg.TransactionTime)
	var balance string
	err := row.Scan(&balance)
	return balance, err
}

const getWalletCategoryBreakdown = `-- name: GetWalletCategoryBreakdown :many
SELECT
    wc.id AS category_id,
    wc.name AS category_name,
    wc.type AS category_type,
    COALESCE(SUM(wt.amount), 0)::NUMERIC AS total
FROM wallet_transaction wt
JOIN wallet_category wc ON wc.id = wt.category_id
WHERE wt.wallet_id = $1
  AND wt.transaction_time >= $2
  AND wt.transaction_time < $3
GROUP BY wc.id, wc.name, wc.type
ORDER BY total DESC
`

type GetWalletCategoryBreakdownParams struct {
	WalletID          int64     `json:"wallet_id"`
	TransactionTime   time.Time `json:"transaction_time"`
	TransactionTime_2 time.Time `json:"transaction_time_2"`
}

type GetWalletCategoryBreakdownRow struct {
	CategoryID   int64  `json:"category_id"`
	CategoryName string `json:"category_name"`
	CategoryType string `json:"category_type"`
	Total        string `json:"total"`
}

func (q *Queries) GetWalletCategoryBreakdown(ctx context.Context, arg GetWalletCategoryBreakdownParams) ([]GetWalletCategoryBreakdownRow, error) {
	rows, err := q.db.QueryContext(ctx, getWalletCategoryBreakdown, arg.WalletID, arg.TransactionTime, arg.TransactionTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWalletCategoryBreakdownRow{}
	for rows.Next() {
		var i GetWalletCategoryBreakdownRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryType,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWalletSummary = `-- name: GetWalletSummary :one
SELECT
    COALESCE(SUM(CASE WHEN type IN ('INCOME','TRANSFER_IN','PORTFOLIO_WITHDRAWAL') THEN amount ELSE 0 END), 0)::NUMERIC AS total_income,
    COALESCE(SUM(CASE WHEN type IN ('EXPENSE','TRANSFER_OUT','PORTFOLIO_DEPOSIT') THEN amount ELSE 0 END), 0)::NUMERIC AS total_expense
FROM wallet_transaction
WHERE wallet_id = $1
  AND transaction_time >= $2
  AND transaction_time < $3
`

type GetWalletSummaryParams struct {
	WalletID          int64     `json:"wallet_id"`
	TransactionTime   time.Time `json:"transaction_time"`
	TransactionTime_2 time.Time `json:"transaction_time_2"`
}

type GetWalletSummaryRow struct {
	TotalIncome  string `json:"total_income"`
	TotalExpense string `json:"total_expense"`
}

func (q *Queries) GetWalletSummary(ctx context.Context, arg GetWalletSummaryParams) (GetWalletSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getWalletSummary, arg.WalletID, arg.TransactionTime, arg.TransactionTime_2)
	var i GetWalletSummaryRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpense)
	return i, err
}

const getWalletTransaction = `-- name: GetWalletTransaction :one
SELECT wt.id, wt.wallet_id, wt.type, wt.amount, wt.category_id, wt.related_wallet_id, wt.related_portfolio_id, wt.broker_rate, wt.note, wt.transaction_time, wt.paired_transaction_id, wc.name AS category_name, w2.name AS related_wallet_name
FROM wallet_transaction wt
LEFT JOIN wallet_category wc ON wc.id = wt.category_id
LEFT JOIN wallet w2 ON w2.id = wt.related_wallet_id
WHERE wt.id = $1 AND wt.wallet_id = $2
`

type GetWalletTransactionParams struct {
	ID       int64 `json:"id"`
	WalletID int64 `json:"wallet_id"`
}

type GetWalletTransactionRow struct {
	ID                  int64          `json:"id"`
	WalletID            int64          `json:"wallet_id"`
	Type                string         `json:"type"`
	Amount              string         `json:"amount"`
	CategoryID          sql.NullInt64  `json:"category_id"`
	RelatedWalletID     sql.NullInt64  `json:"related_wallet_id"`
	RelatedPortfolioID  sql.NullInt64  `json:"related_portfolio_id"`
	BrokerRate          sql.NullString `json:"broker_rate"`
	Note                sql.NullString `json:"note"`
	TransactionTime     time.Time      `json:"transaction_time"`
	PairedTransactionID sql.NullInt64  `json:"paired_transaction_id"`
	CategoryName        sql.NullString `json:"category_name"`
	RelatedWalletName   sql.NullString `json:"related_wallet_name"`
}

func (q *Queries) GetWalletTransaction(ctx context.Context, arg GetWalletTransactionParams) (GetWalletTransactionRow, error) {
	row := q.db.QueryRowContext(ctx, getWalletTransaction, arg.ID, arg.WalletID)
	var i GetWalletTransactionRow
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Type,
		&i.Amount,
		&i.CategoryID,
		&i.RelatedWalletID,
		&i.RelatedPortfolioID,
		&i.BrokerRate,
		&i.Note,
		&i.TransactionTime,
		&i.PairedTransactionID,
		&i.CategoryName,
		&i.RelatedWalletName,
	)
	return i, err
}

const listAggregatedWalletTransactions = `-- name: ListAggregatedWalletTransactions :many
SELECT
    wt.id, wt.wallet_id, wt.type, wt.amount, wt.category_id, wt.related_wallet_id, wt.related_portfolio_id, wt.broker_rate, wt.note, wt.transaction_time, wt.paired_transaction_id,
    wc.name AS category_name,
    w.name AS wallet_name,
    w2.name AS related_wallet_name
FROM wallet_transaction wt
JOIN wallet w ON w.id = wt.wallet_id
LEFT JOIN wallet_category wc ON wc.id = wt.category_id
LEFT JOIN wallet w2 ON w2.id = wt.related_wallet_id
WHERE w.user_id = $1
  AND wt.transaction_time >= $2
  AND wt.transaction_time < $3
  AND ($4::bigint = 0 OR wt.wallet_id = $4)
ORDER BY wt.transaction_time DESC, wt.id DESC
LIMIT $5 OFFSET $6
`

type ListAggregatedWalletTransactionsParams struct {
	UserID            int64     `json:"user_id"`
	TransactionTime   time.Time `json:"transaction_time"`
	TransactionTime_2 time.Time `json:"transaction_time_2"`
	Column4           int64     `json:"column_4"`
	Limit             int32     `json:"limit"`
	Offset            int32     `json:"offset"`
}

type ListAggregatedWalletTransactionsRow struct {
	ID                  int64          `json:"id"`
	WalletID            int64          `json:"wallet_id"`
	Type                string         `json:"type"`
	Amount              string         `json:"amount"`
	CategoryID          sql.NullInt64  `json:"category_id"`
	RelatedWalletID     sql.NullInt64  `json:"related_wallet_id"`
	RelatedPortfolioID  sql.NullInt64  `json:"related_portfolio_id"`
	BrokerRate          sql.NullString `json:"broker_rate"`
	Note                sql.NullString `json:"note"`
	TransactionTime     time.Time      `json:"transaction_time"`
	PairedTransactionID sql.NullInt64  `json:"paired_transaction_id"`
	CategoryName        sql.NullString `json:"category_name"`
	WalletName          string         `json:"wallet_name"`
	RelatedWalletName   sql.NullString `json:"related_wallet_name"`
}

func (q *Queries) ListAggregatedWalletTransactions(ctx context.Context, arg ListAggregatedWalletTransactionsParams) ([]ListAggregatedWalletTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAggregatedWalletTransactions,
		arg.UserID,
		arg.TransactionTime,
		arg.TransactionTime_2,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAggregatedWalletTransactionsRow{}
	for rows.Next() {
		var i ListAggregatedWalletTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Type,
			&i.Amount,
			&i.CategoryID,
			&i.RelatedWalletID,
			&i.RelatedPortfolioID,
			&i.BrokerRate,
			&i.Note,
			&i.TransactionTime,
			&i.PairedTransactionID,
			&i.CategoryName,
			&i.WalletName,
			&i.RelatedWalletName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletTransactions = `-- name: ListWalletTransactions :many
SELECT
    wt.id, wt.wallet_id, wt.type, wt.amount, wt.category_id, wt.related_wallet_id, wt.related_portfolio_id, wt.broker_rate, wt.note, wt.transaction_time, wt.paired_transaction_id,
    wc.name AS category_name,
    w2.name AS related_wallet_name
FROM wallet_transaction wt
LEFT JOIN wallet_category wc ON wc.id = wt.category_id
LEFT JOIN wallet w2 ON w2.id = wt.related_wallet_id
WHERE wt.wallet_id = $1
ORDER BY wt.transaction_time DESC
LIMIT $2 OFFSET $3
`

type ListWalletTransactionsParams struct {
	WalletID int64 `json:"wallet_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

type ListWalletTransactionsRow struct {
	ID                  int64          `json:"id"`
	WalletID            int64          `json:"wallet_id"`
	Type                string         `json:"type"`
	Amount              string         `json:"amount"`
	CategoryID          sql.NullInt64  `json:"category_id"`
	RelatedWalletID     sql.NullInt64  `json:"related_wallet_id"`
	RelatedPortfolioID  sql.NullInt64  `json:"related_portfolio_id"`
	BrokerRate          sql.NullString `json:"broker_rate"`
	Note                sql.NullString `json:"note"`
	TransactionTime     time.Time      `json:"transaction_time"`
	PairedTransactionID sql.NullInt64  `json:"paired_transaction_id"`
	CategoryName        sql.NullString `json:"category_name"`
	RelatedWalletName   sql.NullString `json:"related_wallet_name"`
}

func (q *Queries) ListWalletTransactions(ctx context.Context, arg ListWalletTransactionsParams) ([]ListWalletTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWalletTransactions, arg.WalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWalletTransactionsRow{}
	for rows.Next() {
		var i ListWalletTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Type,
			&i.Amount,
			&i.CategoryID,
			&i.RelatedWalletID,
			&i.RelatedPortfolioID,
			&i.BrokerRate,
			&i.Note,
			&i.TransactionTime,
			&i.PairedTransactionID,
			&i.CategoryName,
			&i.RelatedWalletName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletTransactionsByDateRange = `-- name: ListWalletTransactionsByDateRange :many
SELECT
    wt.id, wt.wallet_id, wt.type, wt.amount, wt.category_id, wt.related_wallet_id, wt.related_portfolio_id, wt.broker_rate, wt.note, wt.transaction_time, wt.paired_transaction_id,
    wc.name AS category_name,
    w2.name AS related_wallet_name
FROM wallet_transaction wt
LEFT JOIN wallet_category wc ON wc.id = wt.category_id
LEFT JOIN wallet w2 ON w2.id = wt.related_wallet_id
WHERE wt.wallet_id = $1
  AND wt.transaction_time >= $2
  AND wt.transaction_time < $3
ORDER BY wt.transaction_time DESC
`

type ListWalletTransactionsByDateRangeParams struct {
	WalletID          int64     `json:"wallet_id"`
	TransactionTime   time.Time `json:"transaction_time"`
	TransactionTime_2 time.Time `json:"transaction_time_2"`
}

type ListWalletTransactionsByDateRangeRow struct {
	ID                  int64          `json:"id"`
	WalletID            int64          `json:"wallet_id"`
	Type                string         `json:"type"`
	Amount              string         `json:"amount"`
	CategoryID          sql.NullInt64  `json:"category_id"`
	RelatedWalletID     sql.NullInt64  `json:"related_wallet_id"`
	RelatedPortfolioID  sql.NullInt64  `json:"related_portfolio_id"`
	BrokerRate          sql.NullString `json:"broker_rate"`
	Note                sql.NullString `json:"note"`
	TransactionTime     time.Time      `json:"transaction_time"`
	PairedTransactionID sql.NullInt64  `json:"paired_transaction_id"`
	CategoryName        sql.NullString `json:"category_name"`
	RelatedWalletName   sql.NullString `json:"related_wallet_name"`
}

func (q *Queries) ListWalletTransactionsByDateRange(ctx context.Context, arg ListWalletTransactionsByDateRangeParams) ([]ListWalletTransactionsByDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, listWalletTransactionsByDateRange, arg.WalletID, arg.TransactionTime, arg.TransactionTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWalletTransactionsByDateRangeRow{}
	for rows.Next() {
		var i ListWalletTransactionsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Type,
			&i.Amount,
			&i.CategoryID,
			&i.RelatedWalletID,
			&i.RelatedPortfolioID,
			&i.BrokerRate,
			&i.Note,
			&i.TransactionTime,
			&i.PairedTransactionID,
			&i.CategoryName,
			&i.RelatedWalletName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPairedTransactionID = `-- name: SetPairedTransactionID :exec
UPDATE wallet_transaction SET paired_transaction_id = $2 WHERE id = $1
`

type SetPairedTransactionIDParams struct {
	ID                  int64         `json:"id"`
	PairedTransactionID sql.NullInt64 `json:"paired_transaction_id"`
}

func (q *Queries) SetPairedTransactionID(ctx context.Context, arg SetPairedTransactionIDParams) error {
	_, err := q.db.ExecContext(ctx, setPairedTransactionID, arg.ID, arg.PairedTransactionID)
	return err
}

const updateTransferPair = `-- name: UpdateTransferPair :exec
UPDATE wallet_transaction
SET amount = $2, transaction_time = $3, note = $4
WHERE wallet_transaction.id = $1
   OR wallet_transaction.id = (SELECT paired_transaction_id FROM wallet_transaction wt2 WHERE wt2.id = $1)
`

type UpdateTransferPairParams struct {
	ID              int64          `json:"id"`
	Amount          string         `json:"amount"`
	TransactionTime time.Time      `json:"transaction_time"`
	Note            sql.NullString `json:"note"`
}

func (q *Queries) UpdateTransferPair(ctx context.Context, arg UpdateTransferPairParams) error {
	_, err := q.db.ExecContext(ctx, updateTransferPair,
		arg.ID,
		arg.Amount,
		arg.TransactionTime,
		arg.Note,
	)
	return err
}

const updateWalletTransaction = `-- name: UpdateWalletTransaction :one
UPDATE wallet_transaction
SET type = $3, amount = $4, category_id = $5, note = $6, transaction_time = $7
WHERE id = $1 AND wallet_id = $2
RETURNING id, wallet_id, type, amount, category_id, related_wallet_id, related_portfolio_id, broker_rate, note, transaction_time, paired_transaction_id
`

type UpdateWalletTransactionParams struct {
	ID              int64          `json:"id"`
	WalletID        int64          `json:"wallet_id"`
	Type            string         `json:"type"`
	Amount          string         `json:"amount"`
	CategoryID      sql.NullInt64  `json:"category_id"`
	Note            sql.NullString `json:"note"`
	TransactionTime time.Time      `json:"transaction_time"`
}

func (q *Queries) UpdateWalletTransaction(ctx context.Context, arg UpdateWalletTransactionParams) (WalletTransaction, error) {
	row := q.db.QueryRowContext(ctx, updateWalletTransaction,
		arg.ID,
		arg.WalletID,
		arg.Type,
		arg.Amount,
		arg.CategoryID,
		arg.Note,
		arg.TransactionTime,
	)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Type,
		&i.Amount,
		&i.CategoryID,
		&i.RelatedWalletID,
		&i.RelatedPortfolioID,
		&i.BrokerRate,
		&i.Note,
		&i.TransactionTime,
		&i.PairedTransactionID,
	)
	return i, err
}
