// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallet_category.sql

package db

import (
	"context"
	"database/sql"
)

const createWalletCategory = `-- name: CreateWalletCategory :one
INSERT INTO wallet_category (user_id, name, type, is_system)
VALUES ($1, $2, $3, FALSE)
RETURNING id, user_id, name, type, is_system
`

type CreateWalletCategoryParams struct {
	UserID sql.NullInt64 `json:"user_id"`
	Name   string        `json:"name"`
	Type   string        `json:"type"`
}

func (q *Queries) CreateWalletCategory(ctx context.Context, arg CreateWalletCategoryParams) (WalletCategory, error) {
	row := q.db.QueryRowContext(ctx, createWalletCategory, arg.UserID, arg.Name, arg.Type)
	var i WalletCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.IsSystem,
	)
	return i, err
}

const getWalletCategoryByName = `-- name: GetWalletCategoryByName :one
SELECT id, user_id, name, type, is_system FROM wallet_category
WHERE name = $1 AND (user_id IS NULL OR user_id = $2)
LIMIT 1
`

type GetWalletCategoryByNameParams struct {
	Name   string        `json:"name"`
	UserID sql.NullInt64 `json:"user_id"`
}

func (q *Queries) GetWalletCategoryByName(ctx context.Context, arg GetWalletCategoryByNameParams) (WalletCategory, error) {
	row := q.db.QueryRowContext(ctx, getWalletCategoryByName, arg.Name, arg.UserID)
	var i WalletCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.IsSystem,
	)
	return i, err
}

const listWalletCategories = `-- name: ListWalletCategories :many
SELECT id, user_id, name, type, is_system FROM wallet_category
WHERE (user_id = $1 OR user_id IS NULL)
ORDER BY is_system DESC, name ASC
`

func (q *Queries) ListWalletCategories(ctx context.Context, userID sql.NullInt64) ([]WalletCategory, error) {
	rows, err := q.db.QueryContext(ctx, listWalletCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletCategory{}
	for rows.Next() {
		var i WalletCategory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
