// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallet.sql

package db

import (
	"context"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallet (user_id, name, currency)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, currency, created_time, updated_time
`

type CreateWalletParams struct {
	UserID   int64  `json:"user_id"`
	Name     string `json:"name"`
	Currency string `json:"currency"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, createWallet, arg.UserID, arg.Name, arg.Currency)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}

const deleteWallet = `-- name: DeleteWallet :exec
DELETE FROM wallet WHERE id = $1 AND user_id = $2
`

type DeleteWalletParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteWallet(ctx context.Context, arg DeleteWalletParams) error {
	_, err := q.db.ExecContext(ctx, deleteWallet, arg.ID, arg.UserID)
	return err
}

const getWallet = `-- name: GetWallet :one
SELECT id, user_id, name, currency, created_time, updated_time FROM wallet WHERE id = $1
`

func (q *Queries) GetWallet(ctx context.Context, id int64) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, getWallet, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}

const getWalletForUser = `-- name: GetWalletForUser :one
SELECT id, user_id, name, currency, created_time, updated_time FROM wallet WHERE id = $1 AND user_id = $2
`

type GetWalletForUserParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetWalletForUser(ctx context.Context, arg GetWalletForUserParams) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, getWalletForUser, arg.ID, arg.UserID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}

const listAllWallets = `-- name: ListAllWallets :many
SELECT id, user_id, name, currency, created_time, updated_time FROM wallet ORDER BY id ASC
`

func (q *Queries) ListAllWallets(ctx context.Context) ([]Wallet, error) {
	rows, err := q.db.QueryContext(ctx, listAllWallets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wallet{}
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Currency,
			&i.CreatedTime,
			&i.UpdatedTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletsByUser = `-- name: ListWalletsByUser :many
SELECT id, user_id, name, currency, created_time, updated_time FROM wallet WHERE user_id = $1 ORDER BY created_time ASC
`

func (q *Queries) ListWalletsByUser(ctx context.Context, userID int64) ([]Wallet, error) {
	rows, err := q.db.QueryContext(ctx, listWalletsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wallet{}
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Currency,
			&i.CreatedTime,
			&i.UpdatedTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWalletName = `-- name: UpdateWalletName :one
UPDATE wallet SET name = $2, updated_time = NOW()
WHERE id = $1
RETURNING id, user_id, name, currency, created_time, updated_time
`

type UpdateWalletNameParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateWalletName(ctx context.Context, arg UpdateWalletNameParams) (Wallet, error) {
	row := q.db.QueryRowContext(ctx, updateWalletName, arg.ID, arg.Name)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Currency,
		&i.CreatedTime,
		&i.UpdatedTime,
	)
	return i, err
}
