// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wallet_transaction.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createWalletTransaction = `-- name: CreateWalletTransaction :one
INSERT INTO wallet_transaction (
    wallet_id, type, amount, category_id,
    related_wallet_id, related_portfolio_id, broker_rate, note, transaction_time
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, wallet_id, type, amount, category_id, related_wallet_id, related_portfolio_id, broker_rate, note, transaction_time
`

type CreateWalletTransactionParams struct {
	WalletID           int64          `json:"wallet_id"`
	Type               string         `json:"type"`
	Amount             string         `json:"amount"`
	CategoryID         sql.NullInt64  `json:"category_id"`
	RelatedWalletID    sql.NullInt64  `json:"related_wallet_id"`
	RelatedPortfolioID sql.NullInt64  `json:"related_portfolio_id"`
	BrokerRate         sql.NullString `json:"broker_rate"`
	Note               sql.NullString `json:"note"`
	TransactionTime    time.Time      `json:"transaction_time"`
}

func (q *Queries) CreateWalletTransaction(ctx context.Context, arg CreateWalletTransactionParams) (WalletTransaction, error) {
	row := q.db.QueryRowContext(ctx, createWalletTransaction,
		arg.WalletID,
		arg.Type,
		arg.Amount,
		arg.CategoryID,
		arg.RelatedWalletID,
		arg.RelatedPortfolioID,
		arg.BrokerRate,
		arg.Note,
		arg.TransactionTime,
	)
	var i WalletTransaction
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Type,
		&i.Amount,
		&i.CategoryID,
		&i.RelatedWalletID,
		&i.RelatedPortfolioID,
		&i.BrokerRate,
		&i.Note,
		&i.TransactionTime,
	)
	return i, err
}

const getWalletBalance = `-- name: GetWalletBalance :one
SELECT COALESCE(
    SUM(CASE
        WHEN type IN ('INCOME', 'TRANSFER_IN', 'PORTFOLIO_WITHDRAWAL') THEN amount
        ELSE -amount
    END), 0
)::NUMERIC AS balance
FROM wallet_transaction
WHERE wallet_id = $1
`

func (q *Queries) GetWalletBalance(ctx context.Context, walletID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getWalletBalance, walletID)
	var balance string
	err := row.Scan(&balance)
	return balance, err
}

const listWalletTransactions = `-- name: ListWalletTransactions :many
SELECT
    wt.id, wt.wallet_id, wt.type, wt.amount, wt.category_id, wt.related_wallet_id, wt.related_portfolio_id, wt.broker_rate, wt.note, wt.transaction_time,
    wc.name AS category_name,
    w2.name AS related_wallet_name
FROM wallet_transaction wt
LEFT JOIN wallet_category wc ON wc.id = wt.category_id
LEFT JOIN wallet w2 ON w2.id = wt.related_wallet_id
WHERE wt.wallet_id = $1
ORDER BY wt.transaction_time DESC
LIMIT $2 OFFSET $3
`

type ListWalletTransactionsParams struct {
	WalletID int64 `json:"wallet_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

type ListWalletTransactionsRow struct {
	ID                 int64          `json:"id"`
	WalletID           int64          `json:"wallet_id"`
	Type               string         `json:"type"`
	Amount             string         `json:"amount"`
	CategoryID         sql.NullInt64  `json:"category_id"`
	RelatedWalletID    sql.NullInt64  `json:"related_wallet_id"`
	RelatedPortfolioID sql.NullInt64  `json:"related_portfolio_id"`
	BrokerRate         sql.NullString `json:"broker_rate"`
	Note               sql.NullString `json:"note"`
	TransactionTime    time.Time      `json:"transaction_time"`
	CategoryName       sql.NullString `json:"category_name"`
	RelatedWalletName  sql.NullString `json:"related_wallet_name"`
}

func (q *Queries) ListWalletTransactions(ctx context.Context, arg ListWalletTransactionsParams) ([]ListWalletTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWalletTransactions, arg.WalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWalletTransactionsRow{}
	for rows.Next() {
		var i ListWalletTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.Type,
			&i.Amount,
			&i.CategoryID,
			&i.RelatedWalletID,
			&i.RelatedPortfolioID,
			&i.BrokerRate,
			&i.Note,
			&i.TransactionTime,
			&i.CategoryName,
			&i.RelatedWalletName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
